include(${CMAKE_CURRENT_SOURCE_DIR}/FontLibrary.cmake)
add_sce_font_library(libSceFont)

if(BUILD_TESTING)
    add_test_executable(guest_font_tests ${LIBS_INCLUDE_DIR}/tests/GuestFont.cpp)
    target_include_directories(guest_font_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_font_tests PRIVATE libSceFont libSceFontFt libc)
    add_test(NAME guest_font COMMAND guest_font_tests)
    add_test_executable(guest_system_font_tests ${LIBS_INCLUDE_DIR}/tests/GuestSystemFont.cpp)
    target_include_directories(guest_system_font_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_system_font_tests PRIVATE libSceFont libSceFontFt libc)
    configure_windows_unwind(guest_system_font_tests)
    add_test(NAME guest_system_font COMMAND guest_system_font_tests)
    if(WIN32)
        set_tests_properties(guest_font guest_system_font PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libSceFont>")
    endif()
    add_test_executable(guest_font_writing_line_tests ${LIBS_INCLUDE_DIR}/tests/GuestFontWritingLine.cpp)
    target_include_directories(guest_font_writing_line_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_font_writing_line_tests PRIVATE libSceFont libc)
    configure_windows_unwind(guest_font_writing_line_tests)
    add_test(NAME guest_font_writing_line COMMAND guest_font_writing_line_tests)
    if(WIN32)
        set_tests_properties(guest_font_writing_line PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libSceFont>")
    endif()
endif()

if(BUILD_TESTING)
    foreach(fontVariant IN ITEMS libSceFont libSceFont.native libSceFont-module)
        string(REPLACE "." "_" fontTest ${fontVariant})
        string(REPLACE "-" "_" fontTest ${fontTest})
        add_test_executable(${fontTest}_glyph_render_tests ${CMAKE_CURRENT_SOURCE_DIR}/tests/GlyphRender.cpp)
        target_include_directories(${fontTest}_glyph_render_tests PRIVATE ${LIBS_INCLUDE_DIR})
        target_link_libraries(${fontTest}_glyph_render_tests PRIVATE ${fontVariant} libSceFontFt libc)
        configure_windows_unwind(${fontTest}_glyph_render_tests)
        add_test(NAME ${fontTest}_glyph_render COMMAND ${fontTest}_glyph_render_tests)
        if(WIN32)
            set_tests_properties(${fontTest}_glyph_render PROPERTIES ENVIRONMENT_MODIFICATION
                "PATH=path_list_prepend:$<TARGET_FILE_DIR:${fontVariant}>")
        endif()
    endforeach()
endif()
